### ISSUE TITLE
No access to VADJ

### ISSUE THREAD

**Issue by butchja** [FMCHUB/FMC_FRU_EEPROM_PROGRAMMER#2]
Would be good to have access to the signal.

**Comment by FMCHUB** [comment]
Good idea, the connector P4 now has a port for VADJ in PCB revision B.

**Comment by butchja** [comment]
![fmc_programmer_patch](https://user-images.githubusercontent.com/35661945/107780884-8f58d000-6d47-11eb-854d-cbb3d227f3fa.jpg)
